### PR TITLE
converting arcs to line segments is very inefficient, instead convert to cubic beziers

### PR DESCRIPTION
**Pull request by njhurst**
shamelessly based on https://github.com/fontello/svgpath/blob/master/lib/a2c.js https://github.com/colinmeinke/svg-arc-to-cubic-bezier

### CODE REVIEW

**Comment by mathandy** [comment]
Hi @njhurst, thanks for the PR.  
"converting arcs to line segments" -- when does this happen?  
Look like your PR changes disvg, what's the reason for that?

**Comment by njhurst** [comment]
Golly, it's been a while, let me see if I remember :)
I think the goal was to represent arcs with cubic beziers, so that you're creating say 4 for a 0.4% error, rather than the 100 or so line segments.  This makes things like intersection and arc length much cheaper, as well as the corresponding render time.  I recall it made one of your tests take a 100ms rather than a minute to run to completion.

The change to disvg was factoring out the part that writes svg paths to files from the part that displays so that I can use your library directly in jupyter-python as an inline element.  I should have perhaps made a separate diff for this, but I'm naughty.  Sorry.

**Comment by tatarize** [comment]
There are other speedups that can be done for the linearization. For @abey79's spearheaded a project on `svgelements` to use np arrays to much more quickly convert arcs to points. If you're hyper concerned with speed you'd likely already have numpy.

I think his benchmarks even for the svgpathtools package ( see svgelements/issues#52 ). Had the parallelized version going like 2.7x faster.

---

However, for simply changing Arcs into Beziers, I actually recommend this. I do it myself in places. Arcs are sometimes kinda rude segments and a lot weird.

I think #103 had this and regebro/svg.path#65 has an implementation of some of my code into something more like svg.path-like code. (my `svgelements` project needs arbitrary matrices applied to arcs so the parameterization is completely changed.) I think regebro/svg.path#59 at the bottom I did the actual legwork to convert the function into one that would work in `svgpathtools` as well as `svg.path`. 

It seems like this might be best done by in-place insertion of the bezier curves in place of the arcs. So you have a `Path` class and you you have some graphics library or something that does not include Arcs or does include Arc but only circular arcs but can handle bezier curves. You would then do `path.approximate_arcs_with_cubics()` or `path.approximate_arcs_with_quads()`. These functions would take an `error` parameter, even if it's not implemented. Then regardless of what your path was you'd know it doesn't have any Arcs in it. And you didn't have to linearize the entire shebang and need to deal with 100 points and higher error.

**Comment by njhurst** [comment]
Yeah, there are lots of bigger versions of my patch, I just needed something specific and figured others might benefit.  I'm definitely interested in a fully vectorized version with numpy, but as I've already written one complete library that does these things I didn't want to get drawn in too deeply :-D  

I also have a complete port of libspiro to run on python+svgpathtools, if people are interested in that I can probably work out how to submit a patch.

**Comment by tatarize** [comment]
I'm going to write up an easier patch for this bit of code. That should get accepted more easily since I can generally do the work to prove it it harmless. And it's fairly close already, and I could likely use the code it I'll have to write myself for my project since I already have these functions. And my last pull got added so I've got a place to fork my stuff.

I'm generally getting a more vectorized version but soft requirement on numpy (meerk40t/svgelements#61) . `svgelements` focuses much more directly on doing robust spec-correct parsing of the SVG throughout. So it has a bunch more things in it. And doesn't focus much on the math heavy stuff here. In fact I generally abduct math from this library when it's needed. But, my Arc code is generally parameterized differently so code to get rid or Arcs would help with compatibility.

**Comment by tatarize** [comment]
@njhurst Can you check #130 and tell me if there's something your pull request here could do that that my pull there can't or doesn't. I see that your PR had some special side ability to use the Mortenson approximation for quarter curves. And while that's actually a better than the native 4/3Tan method it does not generalize. Did yours have some functionality I missed?

I mean this is clean enough to get an easy include and those features might need to get a different PR. But, it's worth having you check it out.

**Comment by abey79** [comment]
I haven't looked in the details of this PR but, if Arcs are to be linearised, I'd like to raise awareness for #126.

**Comment by tatarize** [comment]
Having reread it I think he wants arcs replaced with beziers, because lines are too slow. And it's *much* easier replace arcs with beziers if you have the ability to use them and keep using them instead of arcs rather exclusively. This is both true and quite useful for a variety of things. For example transforming things is really hard unless they are made entirely of points like CubicBeziers. You could use the #130 code to make a kind of good enough transformation matrix without doing a radical re-parameterization of arcs like I had to do for `svgelements`.

**Comment by tatarize** [comment]
@njhurst This should maybe be closed. #130 should have this feature covered without issue.

**Comment by mathandy** [comment]
@njhurst I'm closing this per @tatarize's recommendation. If there is reason (e.g. #130 doesn't cover your needs/concerns), please feel free to re-open.

**Comment by njhurst** [comment]
Sure, fine by me!

**Pull request closed without merging**
