### PR TITLE
Added a function to calculate the d for ellipses and circles.

### PR DESCRIPTION
**Pull request by jpcofr**
Change-Id: I58c983153ccf15f954206ec3b6027b38ae35d992

### CODE REVIEW

**Comment by mathandy** [comment]
Cool.  I appreciate it.  
I'll test this out soon and merge it in assuming everything works.

I'd guess you tested this out a bit.  If you kept your tests, please send them to me, it'll likely save me some time making unittests.

**Comment by jpcofr** [comment]
I tested it by feeding a program I'm working on with a simple svg containing only an ellipse tag. I found it functional; nonetheless, I understand the need for unit tests.

**Comment by jpcofr** [comment]
@mathandy Added some tests and a corner case I was not aware of.

**Comment by mathandy** [comment]
Hi @jpcofr I'm trying to make sense of your commits here.  What's with all the changes?  It looks like you've added or removed whitespace from a bunch of lines.  Are all 6 of these commits different?  I appreciate your help, but please clean up you commits if you want me to review them.

**Comment by jpcofr** [comment]
Created a new pull request related to the comments.

**Pull request closed without merging**
