### PR TITLE
relative path support

### PR DESCRIPTION
**Pull request by taoari**

### CODE REVIEW

**Comment by mathandy** [comment]
Hey @taoari, this looks pretty good, thanks for your contribution!  All new features must come with unittests though -- this is stated in the contributor guidelines.

**Comment by taoari** [comment]
@mathandy The unit test is added. I planned to add the test case in test_path.py. But it seems that a lot of tests can not pass. So I created a new file test_path_d.py.

**Comment by mathandy** [comment]
Hey @taori --  yeah, there's [one test](
https://github.com/mathandy/svgpathtools/issues/74) that currently doesn't
pass, which is my fault.  Hopefully that will be fixed soon (my guess is
the test answer is actually wrong, but I'm not sure yet).  Please add your
test to `test_path.py`.

**Comment by taoari** [comment]
@mathandy Done!

**Comment by taoari** [comment]
@mathandy FYI, the test answer is not wrong, it is just half circle: pi*50^2/2. May be the code is wrong.

**Pull request merged**
